version: ''
services:
    db:
        image: 'postgres:latest'
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: admin
          POSTGRES_DB: imob
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"